// tests/session-title.test.ts — what a session is CALLED, and whether it is a session at all.
//
// Both rules here were written against a real transcript store (2026-07-18) and both were failing
// badly on it:
//   · 103 of the newest 200 sessions were titled "<local-command-caveat>Caveat: The messages below
//     were generated by the user while running local commands. DO NOT respond…" — the same string,
//     over and over, because the title fell back to the first user message and nothing checked
//     whether that message was the CLI talking to itself (`isMeta: true`).
//   · 127 of the newest 300 were `/usage` probes: ~3 KB transcripts holding a caveat, a
//     `<command-name>` line and nothing else. Not short conversations — not conversations.
//
// The two are deliberately separate mechanisms and the difference matters: COMMAND_WRAPPER text is
// plumbing to ignore, while a `<scheduled-task name="…">` turn is real work wearing an envelope and
// must be unwrapped, not dropped.

import { expect, test } from 'bun:test'
import {
  describeTaggedText,
  isCommandWrapperText,
  unwrapTaggedText,
} from '../server/src/transcript'

// --- command plumbing, to be ignored -----------------------------------------

test('the local-command caveat is recognized as plumbing', () => {
  expect(
    isCommandWrapperText(
      '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>',
    ),
  ).toBe(true)
})

test('slash-command scaffolding is plumbing', () => {
  // The three lines a `/usage` probe writes. None of them carries isMeta, so the tag scan is the
  // only thing standing between them and the session list.
  expect(isCommandWrapperText('<command-name>/usage</command-name>')).toBe(true)
  expect(isCommandWrapperText('<command-message>usage</command-message>')).toBe(true)
  expect(isCommandWrapperText('<command-args></command-args>')).toBe(true)
})

test('hook and bash echoes are plumbing', () => {
  expect(isCommandWrapperText('<system-reminder>be brief</system-reminder>')).toBe(true)
  expect(isCommandWrapperText('<user-prompt-submit-hook>ran</user-prompt-submit-hook>')).toBe(true)
  expect(isCommandWrapperText('<bash-input>ls -la</bash-input>')).toBe(true)
  expect(isCommandWrapperText('<local-command-stdout>ok</local-command-stdout>')).toBe(true)
})

test('leading whitespace does not smuggle plumbing past the check', () => {
  expect(isCommandWrapperText('\n  <command-name>/usage</command-name>')).toBe(true)
})

test('real prose is never mistaken for plumbing', () => {
  expect(isCommandWrapperText('Fix the spacing above the auto-resume monitor')).toBe(false)
  // A human writing about the tags, rather than the CLI emitting them: the tag is not at the start.
  expect(isCommandWrapperText('why does <command-name> show up in my titles?')).toBe(false)
  // An unrelated tag-shaped opener is real content; only the known plumbing tags are plumbing.
  expect(isCommandWrapperText('<scheduled-task name="nightly">do the thing</scheduled-task>')).toBe(
    false,
  )
  expect(isCommandWrapperText('')).toBe(false)
})

// --- envelopes, to be unwrapped ----------------------------------------------

test('a scheduled task is titled by its name, not its boilerplate', () => {
  // The real case: without this the title was the whole envelope, file path and all.
  const raw =
    '<scheduled-task name="studio-executor-parity-sweep" file="C:\\Users\\blogi\\.claude\\scheduled-tasks\\studio-executor-parity-sweep\\SKILL.md">\nThis is an automated run of a scheduled task. The user is not present to answer questions.'
  expect(unwrapTaggedText(raw)).toBe('studio-executor-parity-sweep')
})

test('an envelope with no name falls back to its body', () => {
  expect(unwrapTaggedText('<wrapper>the actual prompt</wrapper>')).toBe('the actual prompt')
})

test('an empty envelope keeps the original rather than becoming blank', () => {
  // Returning '' here would push the title down to the bare session uuid for no reason.
  expect(unwrapTaggedText('<wrapper></wrapper>')).toBe('<wrapper></wrapper>')
})

test('ordinary text passes through untouched', () => {
  expect(unwrapTaggedText('Fix the queue clear button')).toBe('Fix the queue clear button')
  expect(unwrapTaggedText('a < b and c > d')).toBe('a < b and c > d')
  expect(unwrapTaggedText('')).toBe('')
})

test('unwrapping does not swallow a body that itself contains tags', () => {
  expect(unwrapTaggedText('<outer>keep <b>this</b> text</outer>')).toBe('keep <b>this</b> text')
})

// --- WHERE a title came from -------------------------------------------------
//
// The owner reported threads showing up called "Watcher" when no account, instance or project of
// his was named that, and there was no way to ask the app where the string had come from. Only one
// of the title sources can invent a label like that: an envelope whose `name` attribute is chosen
// by whatever WROTE the envelope — a scheduler, a hook, a harness — rather than by the user or by
// the assistant. describeTaggedText reports that case so the row can say so, and these tests pin
// the distinction, because "it came from a wrapper" and "it is the first thing you said" look
// identical once they are both just a string in a list.

test('an envelope name is reported as an envelope, and names the tag', () => {
  const d = describeTaggedText('<scheduled-task name="nightly-sweep">do the thing</scheduled-task>')
  expect(d).toEqual({ label: 'nightly-sweep', envelope: true, tag: 'scheduled-task' })
})

test('a tag the app has never heard of is reported just the same', () => {
  // Deliberately NOT an allowlist. A wrapper this code does not recognise is exactly the case that
  // needs explaining, so an unknown tag must still be unwrapped AND still be attributable.
  const d = describeTaggedText('<agent name="Watcher">watch the deploy</agent>')
  expect(d).toEqual({ label: 'Watcher', envelope: true, tag: 'agent' })
})

test('a tag whose BODY became the label is not an envelope', () => {
  // The body is the user's own words wearing punctuation. Nobody chose "the actual prompt" as a
  // name, so marking the row "this label came from somewhere else" would be a lie.
  expect(describeTaggedText('<wrapper>the actual prompt</wrapper>')).toEqual({
    label: 'the actual prompt',
    envelope: false,
    tag: null,
  })
})

test('ordinary text carries no provenance at all', () => {
  expect(describeTaggedText('Fix the queue clear button')).toEqual({
    label: 'Fix the queue clear button',
    envelope: false,
    tag: null,
  })
})

test('the old one-string helper still answers exactly what it used to', () => {
  // unwrapTaggedText is now describeTaggedText().label. Every case above the divider still passes,
  // and this pins the two to each other so a future edit cannot fix one and forget the other.
  for (const raw of [
    '<scheduled-task name="nightly-sweep">x</scheduled-task>',
    '<wrapper>the actual prompt</wrapper>',
    '<wrapper></wrapper>',
    'Fix the queue clear button',
    '',
  ]) {
    expect(unwrapTaggedText(raw)).toBe(describeTaggedText(raw).label)
  }
})
