import { afterEach, describe, expect, test } from 'bun:test'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import type { TranscriptItem } from '@shared/protocol'
import { createMediaCache, type MediaCache } from '../../src/media/cache'
import { tailToItems } from '../../src/bridge/external'
import { historyToItems } from '../../src/engine/normalize'
import { classifyUserText, continuationOf, noteOf, taskItemFrom, userTurn, userTurns, type InjectedPart } from '../../src/engine/system-text'

// Real samples, from Jacob's session jsonl (02b95209-..., the screenshot ours-transcript-task-notification.png)
// and other local transcripts; ids and paths kept, long blobs shortened.
const WORKFLOW_DONE = `<task-notification>
<task-id>w5ahe9hto</task-id>
<tool-use-id>toolu_011HebVQBuHoytXnT7iH9VQB</tool-use-id>
<output-file>C:\\Users\\me\\AppData\\Local\\Temp\\claude\\C--Users-me-Desktop-Project-Connections\\02b95209-e131-404d-9fc7-6033f2d04adf\\tasks\\w5ahe9hto.output</output-file>
<status>completed</status>
<summary>Dynamic workflow "Build a real-vs-ours screenshot parity harness, then match every Hydra Desk area to the real Claude Code desktop, then audit it" completed</summary>
<result>{"harness":{"area":"Parity harness (docs/reference/tools/parity.ts, docs/reference/real/scenes.json)","summary":"The parity harness is built and committed as 37e4392. Running \`bun run parity &lt;scene|all&gt;\` builds the web app"}}</result>
<usage><agent_count>3</agent_count><agents_done>3</agents_done><agents_error>0</agents_error><subagent_tokens>539600</subagent_tokens><tool_uses>554</tool_uses><duration_ms>660000</duration_ms></usage>
</task-notification>`

const BASH_DONE = `<task-notification>
<task-id>bovmv81je</task-id>
<tool-use-id>toolu_01AbC</tool-use-id>
<output-file>C:\\Users\\me\\AppData\\Local\\Temp\\claude\\x\\tasks\\bovmv81je.output</output-file>
<status>completed</status>
<summary>Background command "bun test ./server/test" completed (exit code 0)</summary>
</task-notification>`

const STALLED = `<task-notification>
<summary>Background task stalled or running long</summary>
</task-notification>
<system-reminder>
Stop hook blocking error from command "Stop": STALLWATCH: a background task needs you now.
</system-reminder>`

const AGENT_DONE = `<task-notification>
<task-id>a8k2m1</task-id>
<status>failed</status>
<summary>Agent "critic: sidebar" finished</summary>
<usage><subagent_tokens>189906</subagent_tokens><tool_uses>78</tool_uses><duration_ms>908339</duration_ms></usage>
</task-notification>`

// Claude Code's notice, on resume, of the tasks the previous session left (one body, several ids, a pseudo id).
const LEFT_BEHIND = `<task-notification>
<task-id>b6o886gzv</task-id><task-id>bhf5zoqj5</task-id><task-id>bnuidvnut</task-id><task-id>__orphan_summary__:shell</task-id>
<status>stopped</status>
<summary>3 background shell command tasks didn't finish before the previous session ended. Task ids: b6o886gzv, bhf5zoqj5, bnuidvnut</summary>
</task-notification>`

test('a notice naming several tasks settles every one of them and keeps their own descriptions', () => {
  const prev = new Map(['b6o886gzv', 'bhf5zoqj5', 'bnuidvnut'].map((id, n) => [id, { kind: 'task', id: `task:${id}`, ts: n, taskId: id, description: `command ${n}`, status: 'running', taskKind: 'bash' } as const]))
  const parts = classifyUserText(LEFT_BEHIND)
  expect(parts.map((p) => (p.kind === 'task' ? p.task.taskId : p.kind))).toEqual(['b6o886gzv', 'bhf5zoqj5', 'bnuidvnut'])
  for (const p of parts) {
    if (p.kind !== 'task') continue
    const item = taskItemFrom(p.task, prev.get(p.task.taskId), 100)
    expect(item).toMatchObject({ status: 'stopped', description: prev.get(p.task.taskId)!.description, taskKind: 'bash' })
  }
})

const MONITOR = `<task-notification>
<task-id>m1x</task-id>
<summary>Monitor event: "both vitest full runs completing"</summary>
<event>BOTH_COMPLETE</event>
</task-notification>`

const COMMAND = `<command-name>/model</command-name>
            <command-message>model</command-message>
            <command-args>claude-sonnet-5-5</command-args>`

const CAVEAT =
  'Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.'

const cases: { name: string; text: string; meta?: boolean; want: InjectedPart[] }[] = [
  { name: 'plain message', text: 'fix the sidebar please', want: [{ kind: 'user', text: 'fix the sidebar please' }] },
  {
    name: 'workflow notification',
    text: WORKFLOW_DONE,
    want: [
      {
        kind: 'task',
        task: {
          taskId: 'w5ahe9hto',
          status: 'completed',
          description:
            'Build a real-vs-ours screenshot parity harness, then match every Hydra Desk area to the real Claude Code desktop, then audit it',
          summary:
            'Dynamic workflow "Build a real-vs-ours screenshot parity harness, then match every Hydra Desk area to the real Claude Code desktop, then audit it" completed',
          taskKind: 'workflow',
          toolUseId: 'toolu_011HebVQBuHoytXnT7iH9VQB',
          outputFile:
            'C:\\Users\\me\\AppData\\Local\\Temp\\claude\\C--Users-me-Desktop-Project-Connections\\02b95209-e131-404d-9fc7-6033f2d04adf\\tasks\\w5ahe9hto.output',
          agents: 3,
          tokens: 539600,
          durationMs: 660000,
        },
      },
    ],
  },
  {
    name: 'background command',
    text: BASH_DONE,
    want: [
      {
        kind: 'task',
        task: {
          taskId: 'bovmv81je',
          status: 'completed',
          description: 'bun test ./server/test',
          summary: 'Background command "bun test ./server/test" completed (exit code 0)',
          taskKind: 'bash',
          toolUseId: 'toolu_01AbC',
          outputFile: 'C:\\Users\\me\\AppData\\Local\\Temp\\claude\\x\\tasks\\bovmv81je.output',
        },
      },
    ],
  },
  {
    name: 'agent with usage',
    text: AGENT_DONE,
    want: [
      {
        kind: 'task',
        task: {
          taskId: 'a8k2m1',
          status: 'failed',
          description: 'critic: sidebar',
          summary: 'Agent "critic: sidebar" finished',
          taskKind: 'agent',
          tokens: 189906,
          durationMs: 908339,
        },
      },
    ],
  },
  {
    name: 'monitor event keeps the status',
    text: MONITOR,
    want: [
      {
        kind: 'task',
        task: {
          taskId: 'm1x',
          status: null,
          description: 'both vitest full runs completing',
          summary: 'Monitor event: "both vitest full runs completing": BOTH_COMPLETE',
          taskKind: 'other',
        },
      },
    ],
  },
  { name: 'hook notice without a task id', text: STALLED, want: [{ kind: 'system', text: 'Background task stalled or running long' }] },
  { name: 'system reminder only', text: '<system-reminder>\nYou are in a worktree.\n</system-reminder>', want: [] },
  { name: 'slash command echo', text: COMMAND, want: [{ kind: 'user', text: '/model claude-sonnet-5-5' }] },
  {
    name: 'skill expansion (isMeta)',
    text: '<command-message>workflow-authoring</command-message>\n<command-name>workflow-authoring</command-name>\n<skill-format>true</skill-format>',
    meta: true,
    want: [],
  },
  { name: 'local stdout', text: '<local-command-stdout>Set model to `claude-sonnet-5-5`</local-command-stdout>', want: [{ kind: 'system', text: 'Set model to `claude-sonnet-5-5`' }] },
  { name: 'local stderr', text: '<local-command-stderr>Error: no such skill</local-command-stderr>', want: [{ kind: 'system', text: 'Error: no such skill' }] },
  { name: 'caveat', text: CAVEAT, want: [] },
  { name: 'caveat (meta) wrapper', text: '<local-command-caveat>The command below was run directly in Claude Code.</local-command-caveat>', meta: true, want: [] },
  { name: 'ci monitor event', text: '<ci-monitor-event>checks on #42: 3 passed, 1 failed</ci-monitor-event>', want: [{ kind: 'system', text: 'checks on #42: 3 passed, 1 failed' }] },
  { name: 'unknown wrapper alone', text: '<scheduled-wakeup>resume the audit</scheduled-wakeup>', want: [{ kind: 'system', text: 'resume the audit' }] },
  {
    name: 'stop hook feedback',
    text: 'Stop hook feedback:\n[node hook-dispatch.mjs]: session-commit-gate: 1 file(s) still uncommitted',
    want: [{ kind: 'system', text: 'Stop hook feedback' }],
  },
  {
    name: 'real message mixed with injected blocks',
    text: `<system-reminder>The date changed.</system-reminder>\nCan you also check the <b> tags in README?\n${BASH_DONE}`,
    want: [
      expect.objectContaining({ kind: 'task' }) as unknown as InjectedPart,
      { kind: 'user', text: 'Can you also check the <b> tags in README?' },
    ],
  },
  { name: 'unknown wrapper inside a real message stays', text: 'what does <foo>bar</foo> mean?', want: [{ kind: 'user', text: 'what does <foo>bar</foo> mean?' }] },
]

describe('classifyUserText', () => {
  for (const c of cases) {
    test(c.name, () => {
      expect(classifyUserText(c.text, c.meta)).toEqual(c.want)
    })
  }

  test('never keeps the raw XML or the result blob', () => {
    const parts = classifyUserText(WORKFLOW_DONE)
    const json = JSON.stringify(parts)
    expect(json).not.toContain('<task-id>')
    expect(json).not.toContain('37e4392')
    expect(json).not.toContain('<result>')
  })
})

const rec = (type: string, content: unknown, extra: Record<string, unknown> = {}) => ({
  type,
  uuid: `u${Math.random().toString(36).slice(2)}`,
  timestamp: '2020-10-03T10:00:00.000Z',
  message: { role: type, content },
  ...extra,
})

describe('pasted text', () => {
  test('is the person\'s own text with the pasting wrapper removed', () => {
    const parts = classifyUserText('<pasted_content id="6f84">\nOkay, we do have to fix this.\n</pasted_content>')
    expect(parts).toEqual([{ kind: 'user', text: 'Okay, we do have to fix this.' }])
  })

  test('the closing tag repeats the id, and a cut-off message keeps its text without the tag', () => {
    expect(classifyUserText('<pasted_content id="4431">\nads should be delayed\n</pasted_content id="4431">')).toEqual([{ kind: 'user', text: 'ads should be delayed' }])
    expect(classifyUserText('<pasted_content id="4431">\nads should be delayed')).toEqual([{ kind: 'user', text: 'ads should be delayed' }])
    expect(classifyUserText('before <pasted_content id="1">a</pasted_content id="1"> after')).toEqual([{ kind: 'user', text: 'before a after' }])
  })
})

describe('every path uses the classifier', () => {
  test('history: a notification upserts the running task, never a user bubble', () => {
    const items = historyToItems([
      rec('user', 'start the parity run'),
      { type: 'system', subtype: 'informational', level: 'warning', content: 'heads up', uuid: 'i1', timestamp: '2020-10-03T10:00:01.000Z' },
      rec('user', WORKFLOW_DONE, { origin: { kind: 'task-notification' } }),
      rec('user', COMMAND),
      rec('user', '<local-command-stdout>Set model to `claude-sonnet-5-5`</local-command-stdout>'),
      rec('user', 'This session is being continued from a previous conversation.', { isCompactSummary: true }),
    ])
    const kinds = items.map((i) => i.kind)
    expect(kinds).toEqual(['user', 'system', 'task', 'user', 'system'])
    const users = items.filter((i): i is Extract<TranscriptItem, { kind: 'user' }> => i.kind === 'user').map((u) => u.text)
    expect(users).toEqual(['start the parity run', '/model claude-sonnet-5-5'])
    const task = items.find((i) => i.kind === 'task') as Extract<TranscriptItem, { kind: 'task' }>
    expect(task).toMatchObject({ id: 'task:w5ahe9hto', status: 'completed', taskKind: 'workflow', agents: 3, tokens: 539600 })
  })

  test("AgentHydra's tail: the flattened notification is a task, the same id merges", () => {
    const flat = (s: string) => s.replace(/\s*\n\s*/g, ' ')
    const items = tailToItems({
      session_id: 's1',
      source: 'claude',
      title: 't',
      cwd: 'C:/x',
      events: [
        { role: 'user', kind: 'text', text: 'go', tool_name: null, timestamp: '2020-10-03T10:00:00Z' },
        { role: 'user', kind: 'text', text: flat(MONITOR), tool_name: null, timestamp: '2020-10-03T10:00:01Z' },
        { role: 'user', kind: 'text', text: flat(MONITOR.replace('<summary>', '<status>completed</status><summary>')), tool_name: null, timestamp: '2020-10-03T10:00:02Z' },
      ],
    })
    expect(items.map((i) => i.kind)).toEqual(['user', 'task'])
    expect(items[1]).toMatchObject({ taskId: 'm1x', status: 'completed' })
  })
})

describe("a background task the file shows launched and never settled", () => {
  const launch = (id: string, name: string, script: string, at: string) => [
    rec("assistant", [{ type: "tool_use", id: "tu-" + id, name, input: { script } }], { timestamp: at }),
    rec("user", [{ type: "tool_result", tool_use_id: "tu-" + id, content: "Workflow launched in background. Task ID: " + id }], { timestamp: at }),
  ]

  test("is a running workflow task named from its script, until its notification settles it", () => {
    const script = "export const meta = { name: 'round-three', description: 'd' }"
    const open = historyToItems(launch("wneam8v5j", "Workflow", script, "2020-10-04T08:00:00.000Z"), { now: () => Date.parse("2020-10-04T09:00:00.000Z") })
    expect(open.find((i) => i.kind === "task")).toMatchObject({ id: "task:wneam8v5j", status: "running", taskKind: "workflow", description: "round-three", toolUseId: "tu-wneam8v5j" })
    const done = historyToItems(
      [...launch("w5ahe9hto", "Workflow", script, "2020-10-04T08:00:00.000Z"), rec("user", WORKFLOW_DONE, { origin: { kind: "task-notification" } })],
      { now: () => Date.parse("2020-10-04T09:00:00.000Z") },
    )
    expect(done.filter((i) => i.kind === "task")).toHaveLength(1)
    expect(done.find((i) => i.kind === "task")).toMatchObject({ status: "completed", agents: 3 })
  })

  test("a background command is settled by its queued_command attachment, and a phrase quoted mid-output is no task", () => {
    const bash = [
      rec("assistant", [{ type: "tool_use", id: "tu-b1", name: "Bash", input: { command: "bun test", description: "Run the tests", run_in_background: true } }]),
      rec("user", [{ type: "tool_result", tool_use_id: "tu-b1", content: "Command running in background with ID: bk1. Output is being written to: C:\\x\\bk1.output" }]),
      { type: "attachment", uuid: "a1", timestamp: "2020-10-03T10:05:00.000Z", attachment: { type: "queued_command", prompt: BASH_DONE.replace("bovmv81je", "bk1") } },
      rec("assistant", [{ type: "tool_use", id: "tu-b2", name: "Bash", input: { command: "sed -n 1,5p x.ts" } }]),
      rec("user", [{ type: "tool_result", tool_use_id: "tu-b2", content: "// \"... launched in background. Task ID: x\" or \"Command running in background with ID: y\"" }]),
    ]
    const tasks = historyToItems(bash, { now: () => Date.parse("2020-10-03T10:06:00.000Z") }).filter((i) => i.kind === "task")
    expect(tasks).toHaveLength(1)
    expect(tasks[0]).toMatchObject({ id: "task:bk1", status: "completed", taskKind: "bash", description: "bun test ./server/test" })
  })

  test("is taken as stopped once a day has passed with no notification", () => {
    const items = historyToItems(launch("wold", "Workflow", "", "2020-10-01T08:00:00.000Z"), { now: () => Date.parse("2020-10-04T09:00:00.000Z") })
    expect(items.find((i) => i.kind === "task")).toMatchObject({ status: "stopped" })
  })
})

describe("taskItemFrom", () => {
  test("a notice that settles a running task with no duration of its own records the time from start to notice", () => {
    const prev = { kind: "task" as const, id: "task:t1", ts: 1_000, taskId: "t1", description: "d", status: "running" as const, taskKind: "workflow" as const }
    const item = taskItemFrom({ taskId: "t1", status: "completed", description: "", summary: "", taskKind: "other" }, prev, 61_000)
    expect(item).toMatchObject({ status: "completed", ts: 1_000, durationMs: 60_000 })
  })
  test("a notice with a duration and no start seen started that long before it, so it settles at the notice", () => {
    const item = taskItemFrom({ taskId: "t2", status: "completed", description: "", summary: "", taskKind: "workflow", durationMs: 40_000 }, undefined, 100_000)
    expect(item).toMatchObject({ ts: 60_000, durationMs: 40_000 })
  })
})

// A note AgentHydra types into a session (server/src/climayte-ping.ts shape), with invented content.
const PING = '[AgentHydra · CliMayte] Not from the user. Ping 3-4, 2 updates since 09:00:\n• worker 12 finished: tests pass\n• worker 13 waits on a reply'

describe('notes and picture lines', () => {
  const temps: string[] = []
  afterEach(() => {
    for (const d of temps.splice(0)) rmSync(d, { recursive: true, force: true })
  })
  function png(): { media: MediaCache; file: string } {
    const dir = mkdtempSync(join(tmpdir(), 'desk-note-'))
    temps.push(dir)
    const file = join(dir, 'shot.png')
    writeFileSync(file, new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 1, 2, 3, 4]))
    return { media: createMediaCache(join(dir, 'media')), file }
  }
  const user = (text: string, over: Partial<Extract<TranscriptItem, { kind: 'user' }>> = {}): Extract<TranscriptItem, { kind: 'user' }> => ({
    kind: 'user',
    id: 'u1',
    ts: 5,
    text,
    ...over,
  })

  test('noteOf reads the sender and the body; the person\'s text, or the words further in, are not a note', () => {
    expect(noteOf(PING)).toEqual({ from: 'AgentHydra · CliMayte', text: 'Ping 3-4, 2 updates since 09:00:\n• worker 12 finished: tests pass\n• worker 13 waits on a reply' })
    expect(noteOf('please fix the build')).toBeNull()
    expect(noteOf('he wrote "[AgentHydra] Not from the user." in the log')).toBeNull()
  })

  test('a note keeps its id, time and sub-agent and is never a user item', () => {
    const note = userTurn(user(PING, { parentToolUseId: null, queued: true }), null)
    expect(note).toEqual({ kind: 'note', id: 'u1', ts: 5, parentToolUseId: null, from: 'AgentHydra · CliMayte', text: noteOf(PING)!.text })
  })

  test('a message sent now reads as the person typed it, without the preface AgentHydra gave the worker', () => {
    const preface = '[Sent now: the user stopped your previous turn mid-step to send this message. Act on it first.]'
    expect(userTurn(user(`${preface}\n\nfix the build first`), null)).toMatchObject({ kind: 'user', text: 'fix the build first' })
    // Only as the preface: the same words further in are the person's.
    expect(userTurn(user(`see ${preface}\nthere`), null)).toMatchObject({ text: `see ${preface}\nthere` })
  })

  test("a message sent now as an urgent message (an AgentHydra without deliver-now) reads without AgentHydra's preface", () => {
    const urgent =
      'AgentHydra stopped your previous turn mid-step to deliver this message from the orchestrator. Act on it first; then continue the task only if it still applies, checking the state of anything you were in the middle of.'
    expect(userTurn(user(`${urgent}\n\nfix the build first`), null)).toMatchObject({ kind: 'user', text: 'fix the build first' })
    expect(userTurn(user(`see ${urgent}\n\nthere`), null)).toMatchObject({ text: `see ${urgent}\n\nthere` })
  })

  test('a picture line becomes the picture once, a missing file stays as text, plain text is the same item', () => {
    const { media, file } = png()
    const turn = userTurn(user(`look at this\n[Image: source: ${file}]\n[Image: source: ${file}]\n[Image: source: C:/Users/me/gone.png]`), media)
    expect(turn?.kind).toBe('user')
    const u = turn as Extract<TranscriptItem, { kind: 'user' }>
    expect(u.text).toBe('look at this\n[Image: source: C:/Users/me/gone.png]')
    expect(u.images).toHaveLength(1)
    expect(u.images![0]).toMatchObject({ mediaType: 'image/png', name: 'shot.png' })
    expect(u.images![0].url).toStartWith('/api/media/')
    const plain = user('nothing to change')
    expect(userTurn(plain, media)).toBe(plain)
  })

  test('history and the tail show a ping as a note and the person\'s message as theirs', () => {
    const history = historyToItems([rec('user', 'start'), rec('user', PING)])
    expect(history.map((i) => i.kind)).toEqual(['user', 'note'])
    const tail = tailToItems({
      session_id: 's1',
      source: 'claude',
      title: 't',
      cwd: 'C:/x',
      events: [
        { role: 'user', kind: 'text', text: 'go', tool_name: null, timestamp: '2020-10-03T10:00:00Z' },
        { role: 'user', kind: 'text', text: PING, tool_name: null, timestamp: '2020-10-03T10:00:01Z' },
      ],
    })
    expect(tail.map((i) => i.kind)).toEqual(['user', 'note'])
    expect(tail[1]).toMatchObject({ from: 'AgentHydra · CliMayte' })
  })
})

/** A continuation prompt as AgentHydra's continuationPrompt (server/src/climayte-lib.ts) writes one; invented text. */
function continued(o: { messages?: string[]; account?: string; ended?: string } = {}): string {
  const more = o.messages?.length
    ? `\n\nThe orchestrator also sent these messages, which the earlier session did not get to:\n${o.messages.map((m) => `- ${m}`).join('\n')}`
    : ''
  return (
    'Please tidy the example garden plan.\n\n---\n' +
    `An earlier session already worked on this task ${o.account ?? 'on this account'} and ${o.ended ?? 'handed off because its conversation had grown large'}. ` +
    'Continue from its handoff below (also saved at C:/Users/me/.agenthydra/corch/handoffs/w-1.md). Its full transcript is at C:/Users/me/x.jsonl ' +
    'if you need a detail the handoff left out (read it with the Read or Grep tools; it is JSON lines). Do not redo steps it reports finished.' +
    `${more}\n\n--- HANDOFF ---\n# Handoff\n\n## Goal\nTidy the plan.\n- step one done`
  )
}

describe("a handoff's continuation prompt", () => {
  const user = (text: string): Extract<TranscriptItem, { kind: 'user' }> => ({ kind: 'user', id: 'u9', ts: 7, text, parentToolUseId: null })

  test("with no messages it is one muted line saying why, never the task and handoff as a message of the person's", () => {
    expect(userTurn(user(continued()), null)).toEqual({ kind: 'system', id: 'u9', ts: 7, parentToolUseId: null, level: 'info', text: 'Continued in a fresh session: the conversation had grown long.' })
    expect(continuationOf(continued({ account: 'on another account', ended: 'wound down before its usage limit' }))?.line).toBe(
      'Continued in a fresh session on another account: the account neared its usage limit.',
    )
  })

  test("the messages it carries are the person's: one as written, several as the list they were sent as", () => {
    const one = userTurn(user(continued({ messages: ['why did it stop?\nsecond line'] })), null)
    expect(one).toMatchObject({ kind: 'user', id: 'u9', text: 'why did it stop?\nsecond line' })
    const two = userTurn(user(continued({ messages: ['first ask', 'second ask'] })), null)
    expect(two).toMatchObject({ kind: 'user', text: '- first ask\n- second ask' })
  })

  test("a message that only quotes the words is the person's as it stands", () => {
    const quoted = 'what does "An earlier session already worked on this task on this account and" mean?'
    expect(continuationOf(quoted)).toBeNull()
    expect(userTurn(user(quoted), null)).toEqual(user(quoted))
  })

  test("a chat's continuation, with the main-agent sentence, is still a continuation and not the person's message", () => {
    const chat = continued({ messages: ['why did it stop?'] }).replace(
      'Do not redo steps it reports finished.',
      "That session was this chat's main agent before you: you continue as the main agent of the owner's Desk chat, he reads every reply you write, and you orchestrate the work and report to him. Do not redo steps it reports finished.",
    )
    expect(continuationOf(chat)?.line).toBe('Continued in a fresh session: the conversation had grown long.')
    expect(userTurn(user(chat), null)).toMatchObject({ kind: 'user', text: 'why did it stop?' })
  })

  test("pings it carries are AgentHydra's notes, each its own, and only the person's messages between them are theirs", () => {
    const later = '[AgentHydra · CliMayte] Not from the user. Ping 5, 1 update since 09:10:\n• worker 14 finished: done'
    expect(userTurns(user(continued({ messages: [PING, later] })), null)).toEqual([
      { kind: 'note', id: 'u9', ts: 7, parentToolUseId: null, from: 'AgentHydra · CliMayte', text: PING.slice(PING.indexOf('Ping 3-4')) },
      { kind: 'note', id: 'u9:carried:1', ts: 7, parentToolUseId: null, from: 'AgentHydra · CliMayte', text: later.slice(later.indexOf('Ping 5')) },
    ])
    const mixed = userTurns(user(continued({ messages: ['first ask', 'second ask\n- with a list', PING, 'third ask'] })), null)
    expect(mixed.map((i) => [i.kind, i.id, 'text' in i ? i.text : ''])).toEqual([
      ['user', 'u9', '- first ask\n- second ask\n- with a list'],
      ['note', 'u9:carried:1', PING.slice(PING.indexOf('Ping 3-4'))],
      ['user', 'u9:carried:2', 'third ask'],
    ])
    // The person's list alone is unchanged, and userTurns of any other turn is userTurn's.
    const asks = user(continued({ messages: ['first ask', 'second ask'] }))
    expect(userTurns(asks, null)).toEqual([userTurn(asks, null)!])
    expect(userTurns(user(continued()), null)).toEqual([userTurn(user(continued()), null)!])
    expect(userTurns(user('- a list\n- of mine'), null)).toEqual([user('- a list\n- of mine')])
  })

  test('AgentHydra still writes the words this reads', () => {
    const lib = readFileSync(join(import.meta.dir, '../../../../server/src/climayte-lib.ts'), 'utf8')
    // Source text: each `\\n` is the backslash and n its template literal holds.
    expect(lib).toContain('\\n\\n---\\nAn earlier session already worked on this task ${account} and ${ended}. Continue from its handoff below')
    expect(lib).toContain("\\n\\nThe orchestrator also sent these messages, which the earlier session did not get to:\\n${messages.map((m) => `- ${m}`).join('\\n')}")
    expect(lib).toContain('\\n\\n--- HANDOFF ---\\n${handoff}')
    for (const ended of ['handed off because its conversation had grown large', 'handed off when the orchestrator asked it to', 'wound down before its usage limit'])
      expect(lib).toContain(`'${ended}'`)
  })
})

describe("CliMayte's resume prompts", () => {
  // AgentHydra's words (server/src/climayte-lib.ts), exactly as a resumed session's JSONL holds them.
  const MOVED =
    'This session was moved to another account because the previous one reached its usage limit or was signed out. Continue the task exactly where you left off. Do not redo steps that are already finished.'
  const PAUSED =
    'This session was paused because its account reached its usage limit or was signed out, and it can continue now on the same account. Continue the task exactly where you left off. Do not redo steps that are already finished.'
  const INTERRUPTED =
    'This session was interrupted before it finished: its process was stopped (AgentHydra restarted), not by anything you did. Continue the task exactly where you left off. Do not redo steps that are already finished; run a command again only if its result is missing.'
  const TRANSIENT = 'The API was overloaded and this turn stopped part-way. Continue the task exactly where you left off. Do not redo steps that are already finished.'
  const user = (text: string): Extract<TranscriptItem, { kind: 'user' }> => ({ kind: 'user', id: 'u5', ts: 3, text, parentToolUseId: null })

  test("a move is not shown (CliMayte's move line says it); the others are one muted line, never the person's message", () => {
    expect(userTurn(user(MOVED), null)).toBeNull()
    expect(userTurn(user(`${MOVED}\n`), null)).toBeNull()
    expect(userTurn(user(PAUSED), null)).toEqual({ kind: 'system', id: 'u5', ts: 3, parentToolUseId: null, level: 'info', text: 'Continued on the same account once it could run again.' })
    expect(userTurn(user(INTERRUPTED), null)).toMatchObject({ kind: 'system', text: 'Continued after AgentHydra restarted.' })
    expect(userTurn(user(TRANSIENT), null)).toMatchObject({ kind: 'system', text: 'Continued after the API was overloaded.' })
    const history = historyToItems([rec('user', 'tidy the example garden plan'), rec('user', MOVED), rec('user', INTERRUPTED)])
    expect(history.map((i) => i.kind)).toEqual(['user', 'system'])
  })

  test("a message that quotes the words is the person's as it stands", () => {
    const quoted = `why did I see "${MOVED}"?`
    expect(userTurn(user(quoted), null)).toEqual(user(quoted))
  })

  test("a result sent back by a failed verdict is CliMayte's note, not the person's message", () => {
    const back = 'The orchestrator checked your result and it did not pass. What was wrong: the example list is still unsorted.\n\nFix it, prove the fix with a command and what it printed, and report again.'
    expect(userTurn(user(back), null)).toMatchObject({ kind: 'note', from: 'AgentHydra · CliMayte', text: back })
  })

  test('AgentHydra still writes the words this reads', () => {
    const lib = readFileSync(join(import.meta.dir, '../../../../server/src/climayte-lib.ts'), 'utf8')
    for (const prompt of [MOVED, PAUSED, INTERRUPTED, TRANSIENT]) expect(lib).toContain(`'${prompt}'`)
    const climayte = readFileSync(join(import.meta.dir, '../../../../server/src/climayte.ts'), 'utf8')
    expect(climayte).toContain("const SENT_BACK = 'The orchestrator checked your result and it did not pass. What was wrong:'")
    // Source text: each `\\n` is the backslash and n its template literal holds.
    expect(climayte).toContain('`${SENT_BACK} ${note}\\n\\nFix it, prove the fix with a command and what it printed, and report again.`')
  })
})
