import { afterEach, describe, expect, test } from 'bun:test'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import type { TranscriptItem } from '@shared/protocol'
import { createMediaCache, type MediaCache } from '../../src/media/cache'
import { tailToItems } from '../../src/bridge/external'
import { historyToItems } from '../../src/engine/normalize'
import { classifyUserText, noteOf, taskItemFrom, userTurn, type InjectedPart } from '../../src/engine/system-text'

// Real samples, from Jacob's session jsonl (02b95209-..., the screenshot ours-transcript-task-notification.png)
// and other local transcripts; ids and paths kept, long blobs shortened.
const WORKFLOW_DONE = `<task-notification>
<task-id>w5ahe9hto</task-id>
<tool-use-id>toolu_011HebVQBuHoytXnT7iH9VQB</tool-use-id>
<output-file>C:\\Users\\me\\AppData\\Local\\Temp\\claude\\C--Users-me-Desktop-Project-Connections\\02b95209-e131-404d-9fc7-6033f2d04adf\\tasks\\w5ahe9hto.output</output-file>
<status>completed</status>
<summary>Dynamic workflow "Build a real-vs-ours screenshot parity harness, then match every Hydra Desk area to the real Claude Code desktop, then audit it" completed</summary>
<result>{"harness":{"area":"Parity harness (docs/reference/tools/parity.ts, docs/reference/real/scenes.json)","summary":"The parity harness is built and committed as 37e4392. Running \`bun run parity &lt;scene|all&gt;\` builds the web app"}}</result>
<usage><agent_count>3</agent_count><agents_done>3</agents_done><agents_error>0</agents_error><subagent_tokens>539600</subagent_tokens><tool_uses>554</tool_uses><duration_ms>660000</duration_ms></usage>
</task-notification>`

const BASH_DONE = `<task-notification>
<task-id>bovmv81je</task-id>
<tool-use-id>toolu_01AbC</tool-use-id>
<output-file>C:\\Users\\me\\AppData\\Local\\Temp\\claude\\x\\tasks\\bovmv81je.output</output-file>
<status>completed</status>
<summary>Background command "bun test ./server/test" completed (exit code 0)</summary>
</task-notification>`

const STALLED = `<task-notification>
<summary>Background task stalled or running long</summary>
</task-notification>
<system-reminder>
Stop hook blocking error from command "Stop": STALLWATCH: a background task needs you now.
</system-reminder>`

const AGENT_DONE = `<task-notification>
<task-id>a8k2m1</task-id>
<status>failed</status>
<summary>Agent "critic: sidebar" finished</summary>
<usage><subagent_tokens>189906</subagent_tokens><tool_uses>78</tool_uses><duration_ms>908339</duration_ms></usage>
</task-notification>`

const MONITOR = `<task-notification>
<task-id>m1x</task-id>
<summary>Monitor event: "both vitest full runs completing"</summary>
<event>BOTH_COMPLETE</event>
</task-notification>`

const COMMAND = `<command-name>/model</command-name>
            <command-message>model</command-message>
            <command-args>claude-sonnet-5-5</command-args>`

const CAVEAT =
  'Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.'

const cases: { name: string; text: string; meta?: boolean; want: InjectedPart[] }[] = [
  { name: 'plain message', text: 'fix the sidebar please', want: [{ kind: 'user', text: 'fix the sidebar please' }] },
  {
    name: 'workflow notification',
    text: WORKFLOW_DONE,
    want: [
      {
        kind: 'task',
        task: {
          taskId: 'w5ahe9hto',
          status: 'completed',
          description:
            'Build a real-vs-ours screenshot parity harness, then match every Hydra Desk area to the real Claude Code desktop, then audit it',
          summary:
            'Dynamic workflow "Build a real-vs-ours screenshot parity harness, then match every Hydra Desk area to the real Claude Code desktop, then audit it" completed',
          taskKind: 'workflow',
          toolUseId: 'toolu_011HebVQBuHoytXnT7iH9VQB',
          outputFile:
            'C:\\Users\\me\\AppData\\Local\\Temp\\claude\\C--Users-me-Desktop-Project-Connections\\02b95209-e131-404d-9fc7-6033f2d04adf\\tasks\\w5ahe9hto.output',
          agents: 3,
          tokens: 539600,
          durationMs: 660000,
        },
      },
    ],
  },
  {
    name: 'background command',
    text: BASH_DONE,
    want: [
      {
        kind: 'task',
        task: {
          taskId: 'bovmv81je',
          status: 'completed',
          description: 'bun test ./server/test',
          summary: 'Background command "bun test ./server/test" completed (exit code 0)',
          taskKind: 'bash',
          toolUseId: 'toolu_01AbC',
          outputFile: 'C:\\Users\\me\\AppData\\Local\\Temp\\claude\\x\\tasks\\bovmv81je.output',
        },
      },
    ],
  },
  {
    name: 'agent with usage',
    text: AGENT_DONE,
    want: [
      {
        kind: 'task',
        task: {
          taskId: 'a8k2m1',
          status: 'failed',
          description: 'critic: sidebar',
          summary: 'Agent "critic: sidebar" finished',
          taskKind: 'agent',
          tokens: 189906,
          durationMs: 908339,
        },
      },
    ],
  },
  {
    name: 'monitor event keeps the status',
    text: MONITOR,
    want: [
      {
        kind: 'task',
        task: {
          taskId: 'm1x',
          status: null,
          description: 'both vitest full runs completing',
          summary: 'Monitor event: "both vitest full runs completing": BOTH_COMPLETE',
          taskKind: 'other',
        },
      },
    ],
  },
  { name: 'hook notice without a task id', text: STALLED, want: [{ kind: 'system', text: 'Background task stalled or running long' }] },
  { name: 'system reminder only', text: '<system-reminder>\nYou are in a worktree.\n</system-reminder>', want: [] },
  { name: 'slash command echo', text: COMMAND, want: [{ kind: 'user', text: '/model claude-sonnet-5-5' }] },
  {
    name: 'skill expansion (isMeta)',
    text: '<command-message>workflow-authoring</command-message>\n<command-name>workflow-authoring</command-name>\n<skill-format>true</skill-format>',
    meta: true,
    want: [],
  },
  { name: 'local stdout', text: '<local-command-stdout>Set model to `claude-sonnet-5-5`</local-command-stdout>', want: [{ kind: 'system', text: 'Set model to `claude-sonnet-5-5`' }] },
  { name: 'local stderr', text: '<local-command-stderr>Error: no such skill</local-command-stderr>', want: [{ kind: 'system', text: 'Error: no such skill' }] },
  { name: 'caveat', text: CAVEAT, want: [] },
  { name: 'caveat (meta) wrapper', text: '<local-command-caveat>The command below was run directly in Claude Code.</local-command-caveat>', meta: true, want: [] },
  { name: 'ci monitor event', text: '<ci-monitor-event>checks on #42: 3 passed, 1 failed</ci-monitor-event>', want: [{ kind: 'system', text: 'checks on #42: 3 passed, 1 failed' }] },
  { name: 'unknown wrapper alone', text: '<scheduled-wakeup>resume the audit</scheduled-wakeup>', want: [{ kind: 'system', text: 'resume the audit' }] },
  {
    name: 'stop hook feedback',
    text: 'Stop hook feedback:\n[node hook-dispatch.mjs]: session-commit-gate: 1 file(s) still uncommitted',
    want: [{ kind: 'system', text: 'Stop hook feedback' }],
  },
  {
    name: 'real message mixed with injected blocks',
    text: `<system-reminder>The date changed.</system-reminder>\nCan you also check the <b> tags in README?\n${BASH_DONE}`,
    want: [
      expect.objectContaining({ kind: 'task' }) as unknown as InjectedPart,
      { kind: 'user', text: 'Can you also check the <b> tags in README?' },
    ],
  },
  { name: 'unknown wrapper inside a real message stays', text: 'what does <foo>bar</foo> mean?', want: [{ kind: 'user', text: 'what does <foo>bar</foo> mean?' }] },
]

describe('classifyUserText', () => {
  for (const c of cases) {
    test(c.name, () => {
      expect(classifyUserText(c.text, c.meta)).toEqual(c.want)
    })
  }

  test('never keeps the raw XML or the result blob', () => {
    const parts = classifyUserText(WORKFLOW_DONE)
    const json = JSON.stringify(parts)
    expect(json).not.toContain('<task-id>')
    expect(json).not.toContain('37e4392')
    expect(json).not.toContain('<result>')
  })
})

const rec = (type: string, content: unknown, extra: Record<string, unknown> = {}) => ({
  type,
  uuid: `u${Math.random().toString(36).slice(2)}`,
  timestamp: '2026-10-03T10:00:00.000Z',
  message: { role: type, content },
  ...extra,
})

describe('pasted text', () => {
  test('is the person\'s own text with the pasting wrapper removed', () => {
    const parts = classifyUserText('<pasted_content id="6f84">\nOkay, we do have to fix this.\n</pasted_content>')
    expect(parts).toEqual([{ kind: 'user', text: 'Okay, we do have to fix this.' }])
  })

  test('the closing tag repeats the id, and a cut-off message keeps its text without the tag', () => {
    expect(classifyUserText('<pasted_content id="4431">\nads should be delayed\n</pasted_content id="4431">')).toEqual([{ kind: 'user', text: 'ads should be delayed' }])
    expect(classifyUserText('<pasted_content id="4431">\nads should be delayed')).toEqual([{ kind: 'user', text: 'ads should be delayed' }])
    expect(classifyUserText('before <pasted_content id="1">a</pasted_content id="1"> after')).toEqual([{ kind: 'user', text: 'before a after' }])
  })
})

describe('every path uses the classifier', () => {
  test('history: a notification upserts the running task, never a user bubble', () => {
    const items = historyToItems([
      rec('user', 'start the parity run'),
      { type: 'system', subtype: 'informational', level: 'warning', content: 'heads up', uuid: 'i1', timestamp: '2026-10-03T10:00:01.000Z' },
      rec('user', WORKFLOW_DONE, { origin: { kind: 'task-notification' } }),
      rec('user', COMMAND),
      rec('user', '<local-command-stdout>Set model to `claude-sonnet-5-5`</local-command-stdout>'),
      rec('user', 'This session is being continued from a previous conversation.', { isCompactSummary: true }),
    ])
    const kinds = items.map((i) => i.kind)
    expect(kinds).toEqual(['user', 'system', 'task', 'user', 'system'])
    const users = items.filter((i): i is Extract<TranscriptItem, { kind: 'user' }> => i.kind === 'user').map((u) => u.text)
    expect(users).toEqual(['start the parity run', '/model claude-sonnet-5-5'])
    const task = items.find((i) => i.kind === 'task') as Extract<TranscriptItem, { kind: 'task' }>
    expect(task).toMatchObject({ id: 'task:w5ahe9hto', status: 'completed', taskKind: 'workflow', agents: 3, tokens: 539600 })
  })

  test("AgentHydra's tail: the flattened notification is a task, the same id merges", () => {
    const flat = (s: string) => s.replace(/\s*\n\s*/g, ' ')
    const items = tailToItems({
      session_id: 's1',
      source: 'claude',
      title: 't',
      cwd: 'C:/x',
      events: [
        { role: 'user', kind: 'text', text: 'go', tool_name: null, timestamp: '2026-10-03T10:00:00Z' },
        { role: 'user', kind: 'text', text: flat(MONITOR), tool_name: null, timestamp: '2026-10-03T10:00:01Z' },
        { role: 'user', kind: 'text', text: flat(MONITOR.replace('<summary>', '<status>completed</status><summary>')), tool_name: null, timestamp: '2026-10-03T10:00:02Z' },
      ],
    })
    expect(items.map((i) => i.kind)).toEqual(['user', 'task'])
    expect(items[1]).toMatchObject({ taskId: 'm1x', status: 'completed' })
  })
})

describe("a background task the file shows launched and never settled", () => {
  const launch = (id: string, name: string, script: string, at: string) => [
    rec("assistant", [{ type: "tool_use", id: "tu-" + id, name, input: { script } }], { timestamp: at }),
    rec("user", [{ type: "tool_result", tool_use_id: "tu-" + id, content: "Workflow launched in background. Task ID: " + id }], { timestamp: at }),
  ]

  test("is a running workflow task named from its script, until its notification settles it", () => {
    const script = "export const meta = { name: 'round-three', description: 'd' }"
    const open = historyToItems(launch("wneam8v5j", "Workflow", script, "2026-10-04T08:00:00.000Z"), { now: () => Date.parse("2026-10-04T09:00:00.000Z") })
    expect(open.find((i) => i.kind === "task")).toMatchObject({ id: "task:wneam8v5j", status: "running", taskKind: "workflow", description: "round-three", toolUseId: "tu-wneam8v5j" })
    const done = historyToItems(
      [...launch("w5ahe9hto", "Workflow", script, "2026-10-04T08:00:00.000Z"), rec("user", WORKFLOW_DONE, { origin: { kind: "task-notification" } })],
      { now: () => Date.parse("2026-10-04T09:00:00.000Z") },
    )
    expect(done.filter((i) => i.kind === "task")).toHaveLength(1)
    expect(done.find((i) => i.kind === "task")).toMatchObject({ status: "completed", agents: 3 })
  })

  test("a background command is settled by its queued_command attachment, and a phrase quoted mid-output is no task", () => {
    const bash = [
      rec("assistant", [{ type: "tool_use", id: "tu-b1", name: "Bash", input: { command: "bun test", description: "Run the tests", run_in_background: true } }]),
      rec("user", [{ type: "tool_result", tool_use_id: "tu-b1", content: "Command running in background with ID: bk1. Output is being written to: C:\\x\\bk1.output" }]),
      { type: "attachment", uuid: "a1", timestamp: "2026-10-03T10:05:00.000Z", attachment: { type: "queued_command", prompt: BASH_DONE.replace("bovmv81je", "bk1") } },
      rec("assistant", [{ type: "tool_use", id: "tu-b2", name: "Bash", input: { command: "sed -n 1,5p x.ts" } }]),
      rec("user", [{ type: "tool_result", tool_use_id: "tu-b2", content: "// \"... launched in background. Task ID: x\" or \"Command running in background with ID: y\"" }]),
    ]
    const tasks = historyToItems(bash, { now: () => Date.parse("2026-10-03T10:06:00.000Z") }).filter((i) => i.kind === "task")
    expect(tasks).toHaveLength(1)
    expect(tasks[0]).toMatchObject({ id: "task:bk1", status: "completed", taskKind: "bash", description: "bun test ./server/test" })
  })

  test("is taken as stopped once a day has passed with no notification", () => {
    const items = historyToItems(launch("wold", "Workflow", "", "2026-10-01T08:00:00.000Z"), { now: () => Date.parse("2026-10-04T09:00:00.000Z") })
    expect(items.find((i) => i.kind === "task")).toMatchObject({ status: "stopped" })
  })
})

describe("taskItemFrom", () => {
  test("a notice that settles a running task with no duration of its own records the time from start to notice", () => {
    const prev = { kind: "task" as const, id: "task:t1", ts: 1_000, taskId: "t1", description: "d", status: "running" as const, taskKind: "workflow" as const }
    const item = taskItemFrom({ taskId: "t1", status: "completed", description: "", summary: "", taskKind: "other" }, prev, 61_000)
    expect(item).toMatchObject({ status: "completed", ts: 1_000, durationMs: 60_000 })
  })
  test("a notice with a duration and no start seen started that long before it, so it settles at the notice", () => {
    const item = taskItemFrom({ taskId: "t2", status: "completed", description: "", summary: "", taskKind: "workflow", durationMs: 40_000 }, undefined, 100_000)
    expect(item).toMatchObject({ ts: 60_000, durationMs: 40_000 })
  })
})

// A note AgentHydra types into a session (server/src/climayte-ping.ts shape), with invented content.
const PING = '[AgentHydra · CliMayte] Not from the user. Ping 3-4, 2 updates since 09:00:\n• worker 12 finished: tests pass\n• worker 13 waits on a reply'

describe('notes and picture lines', () => {
  const temps: string[] = []
  afterEach(() => {
    for (const d of temps.splice(0)) rmSync(d, { recursive: true, force: true })
  })
  function png(): { media: MediaCache; file: string } {
    const dir = mkdtempSync(join(tmpdir(), 'desk-note-'))
    temps.push(dir)
    const file = join(dir, 'shot.png')
    writeFileSync(file, new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 1, 2, 3, 4]))
    return { media: createMediaCache(join(dir, 'media')), file }
  }
  const user = (text: string, over: Partial<Extract<TranscriptItem, { kind: 'user' }>> = {}): Extract<TranscriptItem, { kind: 'user' }> => ({
    kind: 'user',
    id: 'u1',
    ts: 5,
    text,
    ...over,
  })

  test('noteOf reads the sender and the body; the person\'s text, or the words further in, are not a note', () => {
    expect(noteOf(PING)).toEqual({ from: 'AgentHydra · CliMayte', text: 'Ping 3-4, 2 updates since 09:00:\n• worker 12 finished: tests pass\n• worker 13 waits on a reply' })
    expect(noteOf('please fix the build')).toBeNull()
    expect(noteOf('he wrote "[AgentHydra] Not from the user." in the log')).toBeNull()
  })

  test('a note keeps its id, time and sub-agent and is never a user item', () => {
    const note = userTurn(user(PING, { parentToolUseId: null, queued: true }), null)
    expect(note).toEqual({ kind: 'note', id: 'u1', ts: 5, parentToolUseId: null, from: 'AgentHydra · CliMayte', text: noteOf(PING)!.text })
  })

  test('a picture line becomes the picture once, a missing file stays as text, plain text is the same item', () => {
    const { media, file } = png()
    const turn = userTurn(user(`look at this\n[Image: source: ${file}]\n[Image: source: ${file}]\n[Image: source: C:/Users/me/gone.png]`), media)
    expect(turn.kind).toBe('user')
    const u = turn as Extract<TranscriptItem, { kind: 'user' }>
    expect(u.text).toBe('look at this\n[Image: source: C:/Users/me/gone.png]')
    expect(u.images).toHaveLength(1)
    expect(u.images![0]).toMatchObject({ mediaType: 'image/png', name: 'shot.png' })
    expect(u.images![0].url).toStartWith('/api/media/')
    const plain = user('nothing to change')
    expect(userTurn(plain, media)).toBe(plain)
  })

  test('history and the tail show a ping as a note and the person\'s message as theirs', () => {
    const history = historyToItems([rec('user', 'start'), rec('user', PING)])
    expect(history.map((i) => i.kind)).toEqual(['user', 'note'])
    const tail = tailToItems({
      session_id: 's1',
      source: 'claude',
      title: 't',
      cwd: 'C:/x',
      events: [
        { role: 'user', kind: 'text', text: 'go', tool_name: null, timestamp: '2026-10-03T10:00:00Z' },
        { role: 'user', kind: 'text', text: PING, tool_name: null, timestamp: '2026-10-03T10:00:01Z' },
      ],
    })
    expect(tail.map((i) => i.kind)).toEqual(['user', 'note'])
    expect(tail[1]).toMatchObject({ from: 'AgentHydra · CliMayte' })
  })
})
