// User-role text that is really the harness talking: Claude Code injects task notifications, system
// reminders, slash-command echoes and local command output into the conversation as user messages.
// Claude Code never draws those as the person's bubble, and neither does Hydra Desk. Pure: one
// classifier used by every path that turns messages into transcript items (the live SDK stream, a
// session's .jsonl, AgentHydra's tail).

import { CONTINUED_LINE, type ImageRef, type TranscriptItem } from '@shared/protocol'
import type { MediaCache } from '../media/cache'

type TaskItem = Extract<TranscriptItem, { kind: 'task' }>
type UserItem = Extract<TranscriptItem, { kind: 'user' }>
type NoteItem = Extract<TranscriptItem, { kind: 'note' }>
type SystemItem = Extract<TranscriptItem, { kind: 'system' }>

/** A <task-notification>, read: the fields the task item carries. Never the raw XML or the result blob. */
export interface TaskNotice {
  taskId: string
  status: TaskItem['status'] | null // null: the notice does not say (a Monitor event), keep the task's own
  description: string
  summary: string
  taskKind: NonNullable<TaskItem['taskKind']>
  toolUseId?: string
  outputFile?: string
  agents?: number
  tokens?: number
  durationMs?: number
}

export type InjectedPart =
  | { kind: 'user'; text: string } // what the person wrote (injected blocks around it removed)
  | { kind: 'task'; task: TaskNotice }
  | { kind: 'system'; text: string } // one muted line

/** Longest muted line or task summary kept; the rest is in the task's output file. */
export const MAX_NOTICE_CHARS = 280

/** The wrapper the app puts around text a person pasted: the text is theirs, the tags are not. The closing tag
 *  repeats the id (</pasted_content id="6f84">); a cut-off message may have lost it, so stray tags go too. */
const PASTED_CONTENT = /<pasted_content id="[^"]*">([\s\S]*?)<\/pasted_content(?: id="[^"]*")?>/g
const PASTED_TAG = /<\/?pasted_content(?: id="[^"]*")?>/g
const CAVEAT = /^\s*Caveat: The messages below were generated by the user while running local commands\.[^\n]*(\n|$)/
const HOOK_FEEDBACK = /^\s*([A-Za-z]+ hook (?:feedback|error|blocking error)[^\n:]*):/
const BLOCK = /<([a-z][a-z0-9_-]*)(?:\s[^>]*)?>([\s\S]*?)<\/\1>/g
/** Wrappers whose content is for the model only: dropped without a line. */
const DROP = new Set([
  'system-reminder',
  'local-command-caveat',
  'skill-format',
  'command-contents',
  'user-prompt-submit-hook',
  'environment_context',
  'ide_opened_file',
  'ide_selection',
])
/** Wrappers that become one muted line of their own text. */
const MUTED = new Set(['local-command-stdout', 'local-command-stderr', 'bash-stdout', 'bash-stderr', 'ci-monitor-event'])

function clip(s: string, n = MAX_NOTICE_CHARS): string {
  const t = s.replace(/\s+/g, ' ').trim()
  return t.length > n ? `${t.slice(0, n - 1)}…` : t
}

function decode(s: string): string {
  return s.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&amp;/g, '&')
}

function field(body: string, name: string): string | null {
  const m = new RegExp(`<${name}>([\\s\\S]*?)</${name}>`).exec(body)
  return m ? decode(m[1]).trim() : null
}

function num(body: string, ...names: string[]): number | undefined {
  for (const name of names) {
    const v = field(body, name)
    if (v !== null && /^\d+$/.test(v)) return Number(v)
  }
  return undefined
}

export function taskKindOf(summary: string): TaskNotice['taskKind'] {
  if (/^Dynamic workflow\b/i.test(summary)) return 'workflow'
  if (/^Background command\b/i.test(summary)) return 'bash'
  if (/^Monitor\b/i.test(summary)) return 'other'
  return 'agent'
}

const STATUS: Record<string, TaskItem['status']> = {
  completed: 'completed',
  failed: 'failed',
  stopped: 'stopped',
  killed: 'stopped',
  cancelled: 'stopped',
  running: 'running',
}

/** Claude Code's notice, on resume, of tasks the previous session left: their own descriptions stay. */
const ENDED_BEFORE = /didn't finish before the previous session ended/i

/**
 * One <task-notification> body: a task notice per task id, or (no task id: a hook's notice) a muted line.
 * Claude Code's resume notice names several tasks in one body (`<task-id>a</task-id><task-id>b</task-id>
 * <task-id>__orphan_summary__:shell</task-id>`); every real id is settled, the `__` pseudo id is not a task.
 * 2026-10-05: only the first was read, so the others stayed 'running' for hours after their session ended.
 */
export function parseTaskNotification(body: string): InjectedPart[] {
  const summary = field(body, 'summary') ?? ''
  const ids = [...body.matchAll(/<task-id>([\s\S]*?)<\/task-id>/g)].map((m) => decode(m[1]).trim()).filter(Boolean)
  if (!ids.length) return summary ? [{ kind: 'system', text: clip(summary) }] : []
  const real = ids.filter((id) => !id.startsWith('__'))
  if (!real.length) return summary ? [{ kind: 'system', text: clip(summary) }] : []
  const rawStatus = field(body, 'status')
  const quoted = /"([^"]+)"/.exec(summary)?.[1]
  const event = field(body, 'event')
  // A notice about several tasks (or about tasks a previous session left) describes none of them alone.
  const shared = real.length > 1 || ENDED_BEFORE.test(summary)
  const toolUseId = field(body, 'tool-use-id')
  const outputFile = field(body, 'output-file')
  const agents = num(body, 'agent_count', 'agents')
  const tokens = num(body, 'subagent_tokens', 'total_tokens', 'tokens')
  const durationMs = num(body, 'duration_ms')
  return real.map((taskId) => {
    const task: TaskNotice = {
      taskId,
      status: rawStatus ? (STATUS[rawStatus.toLowerCase()] ?? 'completed') : null,
      description: shared ? '' : clip(quoted ?? summary, 160),
      summary: clip(event ? `${summary}: ${event}` : summary),
      taskKind: shared ? 'other' : taskKindOf(summary),
    }
    if (!shared) {
      if (toolUseId) task.toolUseId = toolUseId
      if (outputFile) task.outputFile = outputFile
      if (agents !== undefined) task.agents = agents
      if (tokens !== undefined) task.tokens = tokens
      if (durationMs !== undefined) task.durationMs = durationMs
    }
    return { kind: 'task', task }
  })
}

/** '/name args' from a <command-name>/<command-message>/<command-args> echo. */
function commandText(blocks: Map<string, string>): string {
  const name = (blocks.get('command-name') || blocks.get('command-message') || '').trim()
  const args = (blocks.get('command-args') ?? '').trim()
  const slash = name.startsWith('/') ? name : `/${name}`
  return args ? `${slash} ${args}` : slash
}

/**
 * Splits one user-role text into what the transcript shows, in order. A text that is only the person
 * comes back as one 'user' part; injected wrappers become task notices, muted lines or nothing; text
 * between and around them stays the person's. `meta` is Claude Code's isMeta flag (a skill expansion,
 * a caveat): never the person's words.
 */
export function classifyUserText(text: string, meta = false): InjectedPart[] {
  const out: InjectedPart[] = []
  let rest = text.replace(CAVEAT, '').replace(PASTED_CONTENT, '$1').replace(PASTED_TAG, '')
  const hook = HOOK_FEEDBACK.exec(rest)
  if (hook) return [{ kind: 'system', text: clip(hook[1]) }]

  const command = new Map<string, string>()
  const unknown: string[] = []
  let outside = '' // text outside every wrapper
  let kept = '' // the same with unknown wrappers left in place
  let last = 0
  BLOCK.lastIndex = 0
  for (let m = BLOCK.exec(rest); m; m = BLOCK.exec(rest)) {
    outside += rest.slice(last, m.index)
    kept += rest.slice(last, m.index)
    last = m.index + m[0].length
    const [, tag, body] = m
    if (tag === 'task-notification') {
      out.push(...parseTaskNotification(body))
    } else if (tag === 'command-name' || tag === 'command-message' || tag === 'command-args') {
      command.set(tag, decode(body))
    } else if (MUTED.has(tag)) {
      const line = clip(decode(body))
      if (line) out.push({ kind: 'system', text: line })
    } else if (!DROP.has(tag)) {
      unknown.push(body)
      kept += m[0]
    }
  }
  outside += rest.slice(last)
  kept += rest.slice(last)

  // Nothing but wrappers: an unknown one is harness output too (a muted line), never the person.
  if (!outside.trim()) {
    for (const body of unknown) {
      const line = clip(decode(body))
      if (line) out.push({ kind: 'system', text: line })
    }
    rest = ''
  } else rest = kept.trim()

  if (command.size && !meta) out.unshift({ kind: 'user', text: commandText(command) })
  if (rest && !meta) out.push({ kind: 'user', text: rest })
  return out
}

/** The task item a notice upserts: merged over the running one with the same task id when there is one. */
export function taskItemFrom(n: TaskNotice, prev: TaskItem | undefined, ts: number): TaskItem {
  const item: TaskItem = {
    ...(prev ?? { kind: 'task', id: `task:${n.taskId}`, ts, taskId: n.taskId, description: '', status: 'running' }),
  }
  if (n.status) item.status = n.status
  if (!item.description || n.description) item.description = n.description || item.description
  if (n.summary) item.summary = n.summary
  item.taskKind = prev?.taskKind && n.taskKind === 'other' ? prev.taskKind : n.taskKind
  if (n.toolUseId) item.toolUseId = n.toolUseId
  if (n.outputFile) item.outputFile = n.outputFile
  if (n.agents !== undefined) item.agents = n.agents
  if (n.tokens !== undefined) item.tokens = n.tokens
  // ts + durationMs is when it settled, which also places it in its turn (transcript/lib/groups.ts): the
  // notice's own duration, else from the running task's start to the notice; a notice with no start seen
  // started that long before it.
  if (n.durationMs !== undefined) item.durationMs = n.durationMs
  else if (prev?.status === 'running' && n.status && n.status !== 'running') item.durationMs = Math.max(0, ts - prev.ts)
  if (!prev && n.durationMs !== undefined) item.ts = Math.max(0, ts - n.durationMs)
  return item
}

/** A program's message typed in as a user turn: `[AgentHydra · CliMayte] Not from the user. Ping 3, ...`. */
const NOTE = /^\s*\[([^\]\n]{1,80})\]\s+Not from the user\.?[ \t]*\n?/
/** AgentHydra's preface of a held message the person sent now (its SENT_NOW_PREFIX, Send now on a CliMayte chat). */
const SENT_NOW = /^\s*\[Sent now: [^\]\n]*\]\s*\n/
/** AgentHydra's preface of an urgent message (its URGENT_PREFIX): Send now through an AgentHydra without deliver-now. */
const URGENT = /^\s*AgentHydra stopped your previous turn mid-step to deliver this message from the orchestrator\.[^\n]*\n\n/
/** A picture named by its file, the form Claude Code (and a Desk worker's message) uses. */
const PICTURE_LINE = /^[ \t]*\[Image: source: ([^\]\n]+)\][ \t]*(?:\r?\n|$)/gm

/** Who sent a note and what it says; null when the text is the person's. */
export function noteOf(text: string): { from: string; text: string } | null {
  const m = NOTE.exec(text)
  return m ? { from: m[1].trim(), text: text.slice(m[0].length).trim() } : null
}

/** The note AgentHydra's continuationPrompt (server/src/climayte-lib.ts) puts between the task and the rest. */
const CONTINUED = /\n\n---\nAn earlier session already worked on this task (on this account|on another account) and ([^.\n]*)\. Continue from its handoff below/
const HANDOFF_MARK = '\n\n--- HANDOFF ---\n'
/** The messages that session did not get to, `- <message>` each. */
const CONTINUED_MESSAGES = /\n\nThe orchestrator also sent these messages, which the earlier session did not get to:\n([\s\S]*?)\n\n--- HANDOFF ---\n/
const CONTINUED_WHY: [RegExp, string][] = [
  [/conversation had grown large/, 'the conversation had grown long'],
  [/orchestrator asked/, 'it was asked to hand off'],
  [/usage limit/, 'the account neared its usage limit'],
]

/**
 * The first prompt of a session CliMayte continued from a handoff: the task again, a note to the new session,
 * the messages the old one did not get to, and the whole handoff. Only those messages are the person's;
 * `line` says in a few words that the chat went on in a fresh session. Null when the text is not one.
 * 2026-10-05: every such handoff showed the owner the whole prompt as his own message ("I don't want to see
 * the chat that they send to move me over to a new account").
 */
export function continuationOf(text: string): { messages: string | null; line: string } | null {
  const m = CONTINUED.exec(text)
  if (!m || !text.includes(HANDOFF_MARK, m.index)) return null
  const list = CONTINUED_MESSAGES.exec(text.slice(m.index))?.[1]?.trim() ?? ''
  // One message is shown as written; several stay the list they were sent as.
  const messages = list ? (list.startsWith('- ') && !list.includes('\n- ') ? list.slice(2).trim() : list) : null
  const why = CONTINUED_WHY.find(([re]) => re.test(m[2]))?.[1]
  const where = m[1] === 'on another account' ? ' on another account' : ''
  return { messages: messages || null, line: `${CONTINUED_LINE}${where}${why ? `: ${why}` : ''}.` }
}

/**
 * The prompts AgentHydra goes on with a CliMayte worker's own session by (server/src/climayte-lib.ts HANDOFF_PROMPT,
 * PAUSED_PROMPT, INTERRUPTED_PROMPT, TRANSIENT_PROMPT), each with the muted line it is shown as. A move has none:
 * CliMayte's move line ("CliMayte moved this chat from #88 to #83.") already says it. 2026-10-05, owner: "Why am I
 * ever seeing ... 'This session was moved to another account ...' like I sent those words?"
 */
const RESUMED = new Map<string, string | null>([
  [
    'This session was moved to another account because the previous one reached its usage limit or was signed out. Continue the task exactly where you left off. Do not redo steps that are already finished.',
    null,
  ],
  [
    'This session was paused because its account reached its usage limit or was signed out, and it can continue now on the same account. Continue the task exactly where you left off. Do not redo steps that are already finished.',
    'Continued on the same account once it could run again.',
  ],
  [
    'This session was interrupted before it finished: its process was stopped (AgentHydra restarted), not by anything you did. Continue the task exactly where you left off. Do not redo steps that are already finished; run a command again only if its result is missing.',
    'Continued after AgentHydra restarted.',
  ],
  ['The API was overloaded and this turn stopped part-way. Continue the task exactly where you left off. Do not redo steps that are already finished.', 'Continued after the API was overloaded.'],
])
/** A failed verdict sent back to the worker (server/src/climayte.ts SENT_BACK and sendBack). */
const SENT_BACK = /^The orchestrator checked your result and it did not pass\. What was wrong: [\s\S]*\n\nFix it, prove the fix with a command and what it printed, and report again\.$/

/**
 * A user item as the transcript shows it, or null when it is not shown: a note when a program sent it; a
 * handoff's continuation as the messages it carries, or one muted line when it carries none; CliMayte's
 * resume prompts as a muted line, or nothing after a move; else the person's, each
 * `[Image: source: <path>]` line whose file is a picture shown as that picture instead of the line.
 * A line naming a missing file or a non-picture stays as text.
 */
export function userTurn(raw: UserItem, media: Pick<MediaCache, 'fileRef'> | null): UserItem | NoteItem | SystemItem | null {
  const plain = raw.text.trim()
  if (RESUMED.has(plain)) {
    const line = RESUMED.get(plain)
    if (!line) return null
    const { kind: _k, text: _t, images: _i, queued: _q, ...rest } = raw
    return { ...rest, kind: 'system', level: 'info', text: line }
  }
  if (SENT_BACK.test(plain)) {
    const { kind: _k, text: _t, images: _i, queued: _q, ...rest } = raw
    return { ...rest, kind: 'note', from: 'AgentHydra · CliMayte', text: plain }
  }
  const continued = continuationOf(raw.text)
  if (continued && !continued.messages) {
    const { kind: _k, text: _t, images: _i, queued: _q, ...rest } = raw
    return { ...rest, kind: 'system', level: 'info', text: continued.line }
  }
  const said = continued?.messages ? { ...raw, text: continued.messages } : raw
  // A message sent now reads as the person typed it, without the preface that told the worker why its turn ended.
  const preface = SENT_NOW.test(said.text) ? SENT_NOW : URGENT.test(said.text) ? URGENT : null
  const item = preface ? { ...said, text: said.text.replace(preface, '') } : said
  const note = noteOf(item.text)
  if (note) {
    const { kind: _k, text: _t, images: _i, queued: _q, ...rest } = item
    return { ...rest, kind: 'note', from: note.from, text: note.text }
  }
  if (!media || !item.text.includes('[Image: source: ')) return item
  const images: ImageRef[] = [...(item.images ?? [])]
  const text = item.text.replace(PICTURE_LINE, (line, path: string) => {
    const ref = media.fileRef(path.trim())
    if (!ref?.url) return line
    if (!images.some((i) => i.url === ref.url)) images.push(ref)
    return ''
  })
  if (images.length === (item.images?.length ?? 0) && text === item.text) return item
  return { ...item, text: text.trim(), ...(images.length ? { images } : {}) }
}
