// User-role text that is really the harness talking: Claude Code injects task notifications, system
// reminders, slash-command echoes and local command output into the conversation as user messages.
// Claude Code never draws those as the person's bubble, and neither does Hydra Desk. Pure: one
// classifier used by every path that turns messages into transcript items (the live SDK stream, a
// session's .jsonl, AgentHydra's tail).

import type { ImageRef, TranscriptItem } from '@shared/protocol'
import type { MediaCache } from '../media/cache'

type TaskItem = Extract<TranscriptItem, { kind: 'task' }>
type UserItem = Extract<TranscriptItem, { kind: 'user' }>
type NoteItem = Extract<TranscriptItem, { kind: 'note' }>

/** A <task-notification>, read: the fields the task item carries. Never the raw XML or the result blob. */
export interface TaskNotice {
  taskId: string
  status: TaskItem['status'] | null // null: the notice does not say (a Monitor event), keep the task's own
  description: string
  summary: string
  taskKind: NonNullable<TaskItem['taskKind']>
  toolUseId?: string
  outputFile?: string
  agents?: number
  tokens?: number
  durationMs?: number
}

export type InjectedPart =
  | { kind: 'user'; text: string } // what the person wrote (injected blocks around it removed)
  | { kind: 'task'; task: TaskNotice }
  | { kind: 'system'; text: string } // one muted line

/** Longest muted line or task summary kept; the rest is in the task's output file. */
export const MAX_NOTICE_CHARS = 280

/** The wrapper the app puts around text a person pasted: the text is theirs, the tags are not. The closing tag
 *  repeats the id (</pasted_content id="6f84">); a cut-off message may have lost it, so stray tags go too. */
const PASTED_CONTENT = /<pasted_content id="[^"]*">([\s\S]*?)<\/pasted_content(?: id="[^"]*")?>/g
const PASTED_TAG = /<\/?pasted_content(?: id="[^"]*")?>/g
const CAVEAT = /^\s*Caveat: The messages below were generated by the user while running local commands\.[^\n]*(\n|$)/
const HOOK_FEEDBACK = /^\s*([A-Za-z]+ hook (?:feedback|error|blocking error)[^\n:]*):/
const BLOCK = /<([a-z][a-z0-9_-]*)(?:\s[^>]*)?>([\s\S]*?)<\/\1>/g
/** Wrappers whose content is for the model only: dropped without a line. */
const DROP = new Set([
  'system-reminder',
  'local-command-caveat',
  'skill-format',
  'command-contents',
  'user-prompt-submit-hook',
  'environment_context',
  'ide_opened_file',
  'ide_selection',
])
/** Wrappers that become one muted line of their own text. */
const MUTED = new Set(['local-command-stdout', 'local-command-stderr', 'bash-stdout', 'bash-stderr', 'ci-monitor-event'])

function clip(s: string, n = MAX_NOTICE_CHARS): string {
  const t = s.replace(/\s+/g, ' ').trim()
  return t.length > n ? `${t.slice(0, n - 1)}…` : t
}

function decode(s: string): string {
  return s.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&amp;/g, '&')
}

function field(body: string, name: string): string | null {
  const m = new RegExp(`<${name}>([\\s\\S]*?)</${name}>`).exec(body)
  return m ? decode(m[1]).trim() : null
}

function num(body: string, ...names: string[]): number | undefined {
  for (const name of names) {
    const v = field(body, name)
    if (v !== null && /^\d+$/.test(v)) return Number(v)
  }
  return undefined
}

export function taskKindOf(summary: string): TaskNotice['taskKind'] {
  if (/^Dynamic workflow\b/i.test(summary)) return 'workflow'
  if (/^Background command\b/i.test(summary)) return 'bash'
  if (/^Monitor\b/i.test(summary)) return 'other'
  return 'agent'
}

const STATUS: Record<string, TaskItem['status']> = {
  completed: 'completed',
  failed: 'failed',
  stopped: 'stopped',
  killed: 'stopped',
  cancelled: 'stopped',
  running: 'running',
}

/** One <task-notification> body: a task notice, or (no task id: a hook's notice) a muted line. */
export function parseTaskNotification(body: string): InjectedPart | null {
  const summary = field(body, 'summary') ?? ''
  const taskId = field(body, 'task-id')
  if (!taskId) return summary ? { kind: 'system', text: clip(summary) } : null
  const rawStatus = field(body, 'status')
  const quoted = /"([^"]+)"/.exec(summary)?.[1]
  const event = field(body, 'event')
  const task: TaskNotice = {
    taskId,
    status: rawStatus ? (STATUS[rawStatus.toLowerCase()] ?? 'completed') : null,
    description: clip(quoted ?? summary, 160),
    summary: clip(event ? `${summary}: ${event}` : summary),
    taskKind: taskKindOf(summary),
  }
  const toolUseId = field(body, 'tool-use-id')
  const outputFile = field(body, 'output-file')
  if (toolUseId) task.toolUseId = toolUseId
  if (outputFile) task.outputFile = outputFile
  const agents = num(body, 'agent_count', 'agents')
  const tokens = num(body, 'subagent_tokens', 'total_tokens', 'tokens')
  const durationMs = num(body, 'duration_ms')
  if (agents !== undefined) task.agents = agents
  if (tokens !== undefined) task.tokens = tokens
  if (durationMs !== undefined) task.durationMs = durationMs
  return { kind: 'task', task }
}

/** '/name args' from a <command-name>/<command-message>/<command-args> echo. */
function commandText(blocks: Map<string, string>): string {
  const name = (blocks.get('command-name') || blocks.get('command-message') || '').trim()
  const args = (blocks.get('command-args') ?? '').trim()
  const slash = name.startsWith('/') ? name : `/${name}`
  return args ? `${slash} ${args}` : slash
}

/**
 * Splits one user-role text into what the transcript shows, in order. A text that is only the person
 * comes back as one 'user' part; injected wrappers become task notices, muted lines or nothing; text
 * between and around them stays the person's. `meta` is Claude Code's isMeta flag (a skill expansion,
 * a caveat): never the person's words.
 */
export function classifyUserText(text: string, meta = false): InjectedPart[] {
  const out: InjectedPart[] = []
  let rest = text.replace(CAVEAT, '').replace(PASTED_CONTENT, '$1').replace(PASTED_TAG, '')
  const hook = HOOK_FEEDBACK.exec(rest)
  if (hook) return [{ kind: 'system', text: clip(hook[1]) }]

  const command = new Map<string, string>()
  const unknown: string[] = []
  let outside = '' // text outside every wrapper
  let kept = '' // the same with unknown wrappers left in place
  let last = 0
  BLOCK.lastIndex = 0
  for (let m = BLOCK.exec(rest); m; m = BLOCK.exec(rest)) {
    outside += rest.slice(last, m.index)
    kept += rest.slice(last, m.index)
    last = m.index + m[0].length
    const [, tag, body] = m
    if (tag === 'task-notification') {
      const part = parseTaskNotification(body)
      if (part) out.push(part)
    } else if (tag === 'command-name' || tag === 'command-message' || tag === 'command-args') {
      command.set(tag, decode(body))
    } else if (MUTED.has(tag)) {
      const line = clip(decode(body))
      if (line) out.push({ kind: 'system', text: line })
    } else if (!DROP.has(tag)) {
      unknown.push(body)
      kept += m[0]
    }
  }
  outside += rest.slice(last)
  kept += rest.slice(last)

  // Nothing but wrappers: an unknown one is harness output too (a muted line), never the person.
  if (!outside.trim()) {
    for (const body of unknown) {
      const line = clip(decode(body))
      if (line) out.push({ kind: 'system', text: line })
    }
    rest = ''
  } else rest = kept.trim()

  if (command.size && !meta) out.unshift({ kind: 'user', text: commandText(command) })
  if (rest && !meta) out.push({ kind: 'user', text: rest })
  return out
}

/** The task item a notice upserts: merged over the running one with the same task id when there is one. */
export function taskItemFrom(n: TaskNotice, prev: TaskItem | undefined, ts: number): TaskItem {
  const item: TaskItem = {
    ...(prev ?? { kind: 'task', id: `task:${n.taskId}`, ts, taskId: n.taskId, description: '', status: 'running' }),
  }
  if (n.status) item.status = n.status
  if (!item.description || n.description) item.description = n.description || item.description
  if (n.summary) item.summary = n.summary
  item.taskKind = prev?.taskKind && n.taskKind === 'other' ? prev.taskKind : n.taskKind
  if (n.toolUseId) item.toolUseId = n.toolUseId
  if (n.outputFile) item.outputFile = n.outputFile
  if (n.agents !== undefined) item.agents = n.agents
  if (n.tokens !== undefined) item.tokens = n.tokens
  // ts + durationMs is when it settled, which also places it in its turn (transcript/lib/groups.ts): the
  // notice's own duration, else from the running task's start to the notice; a notice with no start seen
  // started that long before it.
  if (n.durationMs !== undefined) item.durationMs = n.durationMs
  else if (prev?.status === 'running' && n.status && n.status !== 'running') item.durationMs = Math.max(0, ts - prev.ts)
  if (!prev && n.durationMs !== undefined) item.ts = Math.max(0, ts - n.durationMs)
  return item
}

/** A program's message typed in as a user turn: `[AgentHydra · CliMayte] Not from the user. Ping 3, ...`. */
const NOTE = /^\s*\[([^\]\n]{1,80})\]\s+Not from the user\.?[ \t]*\n?/
/** AgentHydra's preface of a held message the person sent now (its SENT_NOW_PREFIX, Send now on a CliMayte chat). */
const SENT_NOW = /^\s*\[Sent now: [^\]\n]*\]\s*\n/
/** A picture named by its file, the form Claude Code (and a Desk worker's message) uses. */
const PICTURE_LINE = /^[ \t]*\[Image: source: ([^\]\n]+)\][ \t]*(?:\r?\n|$)/gm

/** Who sent a note and what it says; null when the text is the person's. */
export function noteOf(text: string): { from: string; text: string } | null {
  const m = NOTE.exec(text)
  return m ? { from: m[1].trim(), text: text.slice(m[0].length).trim() } : null
}

/**
 * A user item as the transcript shows it: a note when a program sent it; else the person's, each
 * `[Image: source: <path>]` line whose file is a picture shown as that picture instead of the line.
 * A line naming a missing file or a non-picture stays as text.
 */
export function userTurn(raw: UserItem, media: Pick<MediaCache, 'fileRef'> | null): UserItem | NoteItem {
  // A message sent now reads as the person typed it, without the preface that told the worker why its turn ended.
  const item = SENT_NOW.test(raw.text) ? { ...raw, text: raw.text.replace(SENT_NOW, '') } : raw
  const note = noteOf(item.text)
  if (note) {
    const { kind: _k, text: _t, images: _i, queued: _q, ...rest } = item
    return { ...rest, kind: 'note', from: note.from, text: note.text }
  }
  if (!media || !item.text.includes('[Image: source: ')) return item
  const images: ImageRef[] = [...(item.images ?? [])]
  const text = item.text.replace(PICTURE_LINE, (line, path: string) => {
    const ref = media.fileRef(path.trim())
    if (!ref?.url) return line
    if (!images.some((i) => i.url === ref.url)) images.push(ref)
    return ''
  })
  if (images.length === (item.images?.length ?? 0) && text === item.text) return item
  return { ...item, text: text.trim(), ...(images.length ? { images } : {}) }
}
