# install_switch_card_watchers.ps1 - register (or remove) the Windows task that keeps a card
# watcher running for every account, with NO console window, every few minutes.
#
# WHY NOT schedule_jobs.py: that framework manages the orchestrator's OWN lanes (JOBS / configlib
# JOB_LANES) and its tray arm/disarm. This watcher is deliberately independent of the tray switch
# - the owner asked for it "automatic ... while I sleep" (2026-10-03) - so it is registered under
# its own task name and prefix, and `orch.py schedule_jobs --apply/--remove` never touches it.
# The registration technique is copied from schedule_jobs.py: a wscript VBS shim (window style 0)
# runs the script, because a bare `powershell -WindowStyle Hidden` task action still flashes a
# console on every tick.
#
# Usage:
#   pwsh -NoProfile -File install_switch_card_watchers.ps1                 # register, every 5 min
#   pwsh -NoProfile -File install_switch_card_watchers.ps1 -EveryMinutes 2
#   pwsh -NoProfile -File install_switch_card_watchers.ps1 -Status
#   pwsh -NoProfile -File install_switch_card_watchers.ps1 -Remove
# Exit: 0 ok - 2 schtasks refused - 3 bad usage - 1 not Windows / script missing.
param(
  [ValidateRange(1, 1440)][int]$EveryMinutes = 5,
  [switch]$Status,
  [switch]$Remove
)

if ([Environment]::OSVersion.Platform -ne [PlatformID]::Win32NT) {
  Write-Output 'FAIL: Windows Task Scheduler is the mechanism here - this is Windows-only'
  exit 1
}
$TaskName = 'AgentHydra-SwitchCardWatchers'
$supervisor = Join-Path $PSScriptRoot 'watch_switch_cards.ps1'
$stateRoot = Join-Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) 'state'
$jobsDir = Join-Path $stateRoot 'jobs'
$shim = Join-Path $jobsDir 'switch-card-watchers.vbs'

function Run-Schtasks([string[]]$SchtasksArgs) {
  # NOT named $args: that name collides with PowerShell's automatic variable, `@args` then
  # splats nothing, and bare `schtasks` just LISTS tasks with exit 0 - which read as success
  # while no task was ever created (found 2026-10-03).
  $out = & schtasks @SchtasksArgs 2>&1
  return [pscustomobject]@{ Code = $LASTEXITCODE; Out = (($out | Out-String).Trim()) }
}

if ($Status) {
  $r = Run-Schtasks -SchtasksArgs @('/Query', '/TN', $TaskName, '/V', '/FO', 'LIST')
  if ($r.Code -ne 0) { Write-Output "not registered: $($r.Out)"; exit 0 }
  Write-Output $r.Out
  exit 0
}

if ($Remove) {
  $r = Run-Schtasks -SchtasksArgs @('/Delete', '/TN', $TaskName, '/F')
  $missing = $r.Out -match '(?i)cannot find|does not exist'
  if ($r.Code -ne 0 -and -not $missing) { Write-Output "FAIL: $($r.Out)"; exit 2 }
  Write-Output $(if ($missing) { "was not registered ($TaskName)" } else { "removed $TaskName" })
  exit 0
}

if (-not (Test-Path -LiteralPath $supervisor)) {
  Write-Output "FAIL: $supervisor is missing - nothing to register"
  exit 1
}

# Resolve the interpreter NOW and write its full path into the shim: a scheduled task runs with a
# different environment than a terminal, and `pwsh`/`powershell` may not be on that PATH.
$exe = (Get-Command pwsh -ErrorAction SilentlyContinue).Source
if (-not $exe) { $exe = (Get-Command powershell -ErrorAction SilentlyContinue).Source }
if (-not $exe) { Write-Output 'FAIL: neither pwsh nor powershell is on PATH'; exit 1 }

New-Item -ItemType Directory -Path $jobsDir -Force | Out-Null
# 0 = hidden window; True = wait, so the task's Last Run Result is the supervisor's own exit code.
# ⛔ BUILD THE COMMAND WITH Chr(34), NEVER by embedding quotes: VBScript string escaping plus a
# spaced exe path (`C:\Program Files\...`) is a trap - `rc = sh.Run "cmd"` is a compile error
# ("Expected end of statement"), and `""exe""` closes the literal early ("Expected ')'"), so the
# task runs NOTHING and reports it only as a Last Result number (both hit 2026-10-03).
$vbs = @(
  "' $TaskName - generated by scripts/actuator/install_switch_card_watchers.ps1. Runs the watcher supervisor INVISIBLY.",
  'Set sh = CreateObject("WScript.Shell")',
  'q = Chr(34)',
  ('cmd = q & "{0}" & q & " -NoProfile -ExecutionPolicy Bypass -File " & q & "{1}" & q' -f $exe, $supervisor),
  'rc = sh.Run(cmd, 0, True)',
  'WScript.Quit rc'
) -join "`r`n"
Set-Content -LiteralPath $shim -Value $vbs -Encoding ASCII

$action = 'wscript.exe //B //Nologo "' + $shim + '"'
$r = Run-Schtasks -SchtasksArgs @('/Create', '/TN', $TaskName, '/TR', $action, '/SC', 'MINUTE', '/MO', "$EveryMinutes", '/F')
if ($r.Code -ne 0) { Write-Output "FAIL: schtasks refused to register $TaskName -`n$($r.Out)"; exit 2 }
# A `schtasks /Create` that reports 0 but left nothing queryable must not be called a success.
$check = Run-Schtasks -SchtasksArgs @('/Query', '/TN', $TaskName)
if ($check.Code -ne 0) { Write-Output "FAIL: schtasks reported success but $TaskName is not queryable -`n$($check.Out)"; exit 2 }
Write-Output "registered $TaskName every $EveryMinutes min"
Write-Output "shim: $shim"
Write-Output "supervisor log: $(Join-Path $stateRoot 'logs\watch-switch-cards.log')"
Write-Output ("run it once now to start the watchers without waiting: pwsh -NoProfile -File `"$supervisor`"")
exit 0
