import { afterEach, describe, expect, test } from 'bun:test'
import {
  appendFileSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  type CodexMoveRequest,
  moveCodexChat,
  planCodexChatMove,
} from '../src/core/codex-chat-move'
import type { CodexRpc } from '../src/core/codex-rpc'
import type { CodexInstance } from '../src/types'

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/

const roots: string[] = []
afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true })
})

/** A rollout the copier will accept: exactly one session_meta owning the source id, and a
 * finished turn, so only the tests that mean to trip a rail trip one. */
function rollout(threadId: string, cwd: string): string {
  return `${[
    {
      timestamp: '2026-09-11T21:00:00.000Z',
      type: 'session_meta',
      payload: { id: threadId, session_id: threadId, cwd, originator: 'Codex Desktop' },
    },
    {
      timestamp: '2026-09-11T21:00:01.000Z',
      type: 'event_msg',
      payload: { type: 'task_started', thread_id: threadId, turn_id: 'turn-1' },
    },
    {
      timestamp: '2026-09-11T21:00:02.000Z',
      type: 'response_item',
      payload: { type: 'message', role: 'user', content: [{ type: 'input_text', text: 'First' }] },
    },
    {
      timestamp: '2026-09-11T21:00:03.000Z',
      type: 'event_msg',
      payload: { type: 'task_complete', thread_id: threadId, turn_id: 'turn-1' },
    },
  ]
    .map((row) => JSON.stringify(row))
    .join('\n')}\n`
}

function fixture() {
  const root = mkdtempSync(join(tmpdir(), 'codex-move-'))
  roots.push(root)
  const homes = [join(root, 'source'), join(root, 'target')]
  for (const home of homes) mkdirSync(join(home, 'sessions'), { recursive: true })
  const sourceHome = homes[0]!
  const targetHome = homes[1]!
  const instances = homes.map(
    (home, index) =>
      ({
        id: String(index),
        name: `Account ${index}`,
        codexHome: home,
        isExternal: false,
        account: { authMode: 'chatgpt', accountId: `account-${index}` },
      }) as CodexInstance,
  )
  const thread = {
    id: 'chat-1',
    name: 'My chat',
    preview: 'First message',
    cwd: root,
    path: join(sourceHome, 'sessions', 'chat.jsonl'),
    updatedAt: 100,
    model: 'test-model',
    reasoningEffort: 'high',
  }
  writeFileSync(thread.path, rollout(thread.id, root))
  const calls: string[] = []
  /** What the destination was actually asked to import. The id is generated by the move, so the
   * fake learns it the same way real Codex would: from the resume call. */
  const imported: Record<string, unknown> = {}
  const state = {
    archived: false,
    running: false,
    blockCopy: false,
    failResume: false,
    failArchive: false,
    failRead: false,
    mutateDuringImport: false,
    secondPage: false,
  }
  const connect = async (home: string): Promise<CodexRpc> => {
    const side = home === sourceHome ? 'source' : 'target'
    calls.push(`${side}:connect`)
    return {
      close() {
        calls.push(`${side}:close`)
      },
      async call<T>(method: string, params?: Record<string, unknown>): Promise<T> {
        calls.push(`${side}:${method}`)
        if (method === 'thread/list') {
          expect(params?.archived).toBe(false)
          if (state.secondPage && !params?.cursor)
            return { data: [thread], nextCursor: 'page-2' } as T
          return {
            data: state.archived
              ? []
              : [{ ...thread, ...(params?.cursor ? { id: 'chat-2' } : {}) }],
            nextCursor: null,
          } as T
        }
        if (method === 'thread/resume') {
          Object.assign(imported, params)
          if (state.mutateDuringImport)
            appendFileSync(
              thread.path,
              `${JSON.stringify({
                timestamp: '2026-09-11T21:05:00.000Z',
                type: 'response_item',
                payload: { type: 'message', role: 'user', content: [] },
              })}\n`,
            )
          if (state.failResume) throw new Error('Import failed')
          return {} as T
        }
        if (method === 'thread/name/set') {
          imported.name = params?.name
          return {} as T
        }
        if (method === 'thread/read') {
          if (state.failRead) throw new Error('Verification failed')
          return { thread: { ...thread, id: params?.threadId, path: imported.path } } as T
        }
        if (method === 'thread/archive') {
          if (state.failArchive) throw new Error('Archive failed')
          state.archived = true
        }
        return {} as T
      },
    }
  }
  const deps = {
    getInstance: (id: string) => instances.find((instance) => instance.id === id) ?? null,
    runState: async () =>
      state.running
        ? { state: 'unknown' as const, reason: 'unavailable' }
        : { state: 'stopped' as const },
    connect,
    journalPath: join(root, 'moves.json'),
  }
  const request: CodexMoveRequest = {
    targetId: '1',
    threadId: thread.id,
    updatedAt: thread.updatedAt,
    sourceAccountId: 'account-0',
    targetAccountId: 'account-1',
  }
  /** Every rollout the move wrote into the destination home. */
  const copies = () =>
    readdirSync(join(targetHome, 'sessions'), { recursive: true })
      .map(String)
      .filter((entry) => entry.endsWith('.jsonl'))
  const copyText = () => readFileSync(join(targetHome, 'sessions', copies()[0]!), 'utf8')
  /** Make the destination's dated session folder unwritable, so the copy cannot be confirmed. */
  const datedFolder = () => join(targetHome, 'sessions', new Date().toISOString().slice(0, 4))
  const blockCopy = () => writeFileSync(datedFolder(), 'not a directory')
  const unblockCopy = () => rmSync(datedFolder(), { force: true })
  return {
    root,
    sourceHome,
    targetHome,
    state,
    instances,
    thread,
    calls,
    deps,
    request,
    imported,
    copies,
    copyText,
    blockCopy,
    unblockCopy,
  }
}

describe('Codex chat move', () => {
  test('plans every page of active chats with titles, folders and account identities', async () => {
    const f = fixture()
    f.state.secondPage = true
    const plan = await planCodexChatMove('0', '1', f.deps)
    expect(plan.chats.map((chat) => chat.id)).toEqual(['chat-1', 'chat-2'])
    expect(plan.chats[0]?.title).toBe('My chat')
    expect(plan.sourceAccountId).toBe('account-0')
    expect(f.calls.at(-1)).toBe('source:close')
  })
  test('copies the transcript under a new id and resumes only that copy', async () => {
    const f = fixture()
    const result = await moveCodexChat('0', f.request, f.deps)
    expect(result.ok).toBe(true)
    const id = result.destinationThreadId!
    expect(id).toMatch(UUID)
    // Never a cross-profile fork: the source id does not exist in the destination's database.
    expect(f.calls).not.toContain('target:thread/fork')
    expect(f.imported.threadId).toBe(id)
    expect(f.imported.excludeTurns).toBe(true)
    expect(f.imported.cwd).toBe(f.thread.cwd)
    expect(f.imported.model).toBe('test-model')
    expect(f.imported.config).toEqual({ model_reasoning_effort: 'high' })
    expect(f.imported.name).toBe('My chat')
    expect(String(f.imported.path).startsWith(f.targetHome)).toBe(true)
    expect(f.copies()).toHaveLength(1)
    const copy = f.copyText()
    expect(copy).toContain(id)
    expect(copy).not.toContain('chat-1')
    expect(JSON.parse(copy.split('\n')[0]!).payload.session_id).toBe(id)
    // The source keeps its own transcript byte for byte.
    expect(readFileSync(f.thread.path, 'utf8')).toBe(rollout('chat-1', f.root))
  })
  test('verifies the destination before archiving and repeats without creating a duplicate', async () => {
    const f = fixture()
    const result = await moveCodexChat('0', f.request, f.deps)
    expect(result.ok).toBe(true)
    expect(f.calls.indexOf('target:thread/read')).toBeLessThan(
      f.calls.indexOf('source:thread/archive'),
    )
    expect(f.calls).toContain('target:thread/unsubscribe')
    expect(f.state.archived).toBe(true)
    expect(await moveCodexChat('0', f.request, f.deps)).toEqual(result)
    expect(f.copies()).toHaveLength(1)
    expect(f.calls.filter((call) => call === 'target:thread/resume')).toHaveLength(1)
  })
  test('a failed archive retries the saved copy instead of copying again', async () => {
    const f = fixture()
    f.state.failArchive = true
    const first = await moveCodexChat('0', f.request, f.deps)
    expect(first.ok).toBe(false)
    expect(f.state.archived).toBe(false)
    expect(f.copies()).toHaveLength(1)
    f.state.failArchive = false
    expect(await moveCodexChat('0', f.request, f.deps)).toEqual({
      ok: true,
      destinationThreadId: first.destinationThreadId,
    })
    expect(f.copies()).toHaveLength(1)
  })
  test('an unconfirmed copy never archives and cannot be repeated blindly', async () => {
    const f = fixture()
    f.blockCopy()
    expect((await moveCodexChat('0', f.request, f.deps)).ok).toBe(false)
    expect(f.calls).not.toContain('target:thread/resume')
    f.unblockCopy()
    expect((await moveCodexChat('0', f.request, f.deps)).error).toContain('previous copy')
    expect(f.state.archived).toBe(false)
    expect(f.copies()).toHaveLength(0)
  })
  test('a failed import keeps the copy on disk and never archives the source', async () => {
    const f = fixture()
    f.state.failResume = true
    expect((await moveCodexChat('0', f.request, f.deps)).ok).toBe(false)
    expect(f.calls).not.toContain('source:thread/archive')
    expect(f.copies()).toHaveLength(1)
    f.state.failResume = false
    expect((await moveCodexChat('0', f.request, f.deps)).ok).toBe(true)
    expect(f.copies()).toHaveLength(1)
  })
  test('failed destination verification preserves the original', async () => {
    const f = fixture()
    f.state.failRead = true
    expect((await moveCodexChat('0', f.request, f.deps)).ok).toBe(false)
    expect(f.calls).not.toContain('source:thread/archive')
  })
  test('an unfinished CLI turn cannot be moved even with the desktop stopped', async () => {
    const f = fixture()
    appendFileSync(
      f.thread.path,
      `${JSON.stringify({ type: 'event_msg', payload: { type: 'task_started', turn_id: 'running' } })}\n`,
    )
    expect((await moveCodexChat('0', f.request, f.deps)).error).toContain('unfinished turn')
    expect(f.calls).not.toContain('target:thread/resume')
    expect(f.copies()).toHaveLength(0)
  })
  test('an edit during the import keeps both chats and refuses a stale retry', async () => {
    const f = fixture()
    f.state.mutateDuringImport = true
    expect((await moveCodexChat('0', f.request, f.deps)).error).toContain('source changed')
    expect(f.state.archived).toBe(false)
    expect((await moveCodexChat('0', f.request, f.deps)).error).toContain('source chat changed')
  })
  test('an unknown process state, changed login, or same home refuses before connecting', async () => {
    const f = fixture()
    f.state.running = true
    expect((await moveCodexChat('0', f.request, f.deps)).ok).toBe(false)
    f.state.running = false
    expect(
      (await moveCodexChat('0', { ...f.request, targetAccountId: 'different' }, f.deps)).ok,
    ).toBe(false)
    f.instances[1]!.codexHome = f.instances[0]!.codexHome
    expect((await moveCodexChat('0', f.request, f.deps)).ok).toBe(false)
    expect(f.calls).toEqual([])
  })
  test('rejects archived, changed, or out-of-home transcripts', async () => {
    const f = fixture()
    f.state.archived = true
    expect((await moveCodexChat('0', f.request, f.deps)).ok).toBe(false)
    f.state.archived = false
    expect((await moveCodexChat('0', { ...f.request, updatedAt: 99 }, f.deps)).ok).toBe(false)
    f.thread.path = join(f.root, 'outside.jsonl')
    writeFileSync(f.thread.path, rollout('chat-1', f.root))
    expect((await moveCodexChat('0', f.request, f.deps)).ok).toBe(false)
    expect(f.calls).not.toContain('target:thread/resume')
    expect(f.copies()).toHaveLength(0)
  })
  test('corrupt move history is preserved and prevents any copy', async () => {
    const f = fixture()
    writeFileSync(f.deps.journalPath, '{broken')
    expect((await moveCodexChat('0', f.request, f.deps)).ok).toBe(false)
    expect(readFileSync(f.deps.journalPath, 'utf8')).toBe('{broken')
    expect(f.calls).not.toContain('target:thread/resume')
    expect(f.copies()).toHaveLength(0)
  })
})
